# Site settings
title:              InterruptSpeed
email:              sdocherty@InterruptSpeed.com
description:        This is my container for random things.
url:                https://interruptspeed.github.io/

links:
  - name:         Blog
    url:          /
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/InterruptSpeed
    external:     true
  - name:         Twitter
    url:          http://twitter.com/InterruptSpeed
    external:     true
  - name:         RSS
    url:          /feed.xml


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

  # The following is untested, suppossed to work once Github gets Kramdown 1.6...
  # (current visible at https://pages.github.com/versions)
  math_engine:      mathjax  # default in Kramdown
  math_engine_opts:
    preview: true   # not default but better acessibility

redcarpet:
  extensions:
    - smart
