# Site settings
title:              Imanol Schlag
email:              imanol.schlag@gmail.com

links:
  - name:         Blog
    url:          http://ischlag.github.io
    external:     true
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/ischlag
    external:     true

# Build settings
highlighter:        pygments
markdown:           kramdown
kramdown:
  # The following is untested, suppossed to work once Github gets Kramdown 1.6...
  # (current visible at https://pages.github.com/versions)
  math_engine:      mathjax  # default in Kramdown
  math_engine_opts: preview: true   # not default but better acessibility
redcarpet:
  extensions:
    - smart
